# Generated by Django 4.1.6 on 2023-02-09 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_name_newuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 5, 50, 52, 11489, tzinfo=datetime.timezone.utc)),
        ),
    ]
